on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  # this is the job's id
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there!"
