name: First Action
on:
  workflow_dispatch:
    inputs:
      thename:
        description: "Who should we greet?"
        type: string
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  say_hello_fromAction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/greet-user
        with:
          who_to_greet: ${{ inputs.thename }}
